# Generated by Django 3.0.5 on 2020-05-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
