# Generated by Django 3.0.5 on 2020-06-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
