# Generated by Django 3.0.5 on 2020-05-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system_app', '0003_auto_20200505_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavereportstaff',
            old_name='leave_message',
            new_name='leave_reason',
        ),
        migrations.RenameField(
            model_name='leavereportstudent',
            old_name='leave_message',
            new_name='leave_reason',
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
