# Generated by Django 3.0.5 on 2020-05-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system_app', '0004_auto_20200505_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstaff',
            old_name='feedback',
            new_name='feedback_message',
        ),
    ]
