# Generated by Django 3.0.5 on 2020-05-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system_app', '0005_auto_20200505_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstudent',
            old_name='feedback',
            new_name='feedback_message',
        ),
    ]
